# 2_make_CJFAS_figs_rev1_final.R
# final figures for CJFAS based on first round of reviewer comments

library(ggplot2); library(gridExtra); library(grid); library(ggpubr)
library(dplyr); library(tidyr)

# used for Windows 
windowsFonts(Times=windowsFont("Times New Roman"))
# end used for Windows section

# set working directory to source file location to begin

# specify order for IBMs so Ensemble and SCAA are at the end
IBM_order_new <- rev(c("AIM","CC-FM","CC-FSPR","DynLin","ES-FM","ES-Frecent",
                       "ES-FSPR","ES-Fstable","Islope","Ismooth","Itarget",
                       "Skate","Ensemble","SCAA"))

# get data for final figures
sims <- readRDS("sims.RDS")

# some data wrangling for new and alternative figures
# compute medians by IBMs
medIBM <- sims %>%
  group_by(IBMlab, metric) %>%
  summarize(medval = median(value))

# compute medians by IBMs and Scenarios
medIBMScen <- sims %>%
  group_by(IBMlab, Scenlab, metric) %>%
  summarize(medval = median(value))

# get long term SSB/SSBmsy, F/Fmsy, and C/MSY medians
medlong <- sims %>%
  filter(time.avg == "L",
         metric %in% c("avg_ssb_ssbmsy", "avg_f_fmsy", "avg_catch_msy")) %>%
  group_by(IBMlab, Scenlab, metric) %>%
  summarize(medval = median(value)) %>%
  pivot_wider(names_from = metric, values_from = medval) %>%
  mutate(retro_type = ifelse(substr(Scenlab, 1, 1)=="C", "Catch", "M"))

# medians by retro type and F history
medretro_Fhist <- sims %>%
  group_by(IBMlab, retro_type, Fhist, metric) %>%
  summarize(medval = median(value)) %>%
  mutate(F_history = ifelse(Fhist==1, "Fmsy", "2.5 x Fmsy"),
         Retro_source = retro_type)

# medians by time period and F history for F/Fmsy only
medtime_Fhist <- sims %>%
  filter(metric == "avg_f_fmsy") %>%
  group_by(IBMlab, time.avg, Fhist, metric) %>%
  summarize(medval = median(value)) %>%
  mutate(F_history = ifelse(Fhist==1, "Fmsy", "2.5 x Fmsy"),
         Period = ifelse(time.avg=="L", "Long-term", ifelse(time.avg=="S","Short-term","All years or combined long and short")))

# medians by catch multiplier and F history for F/Fmsy only
medCmult_Fhist <- sims %>%
  filter(metric == "avg_f_fmsy") %>%
  group_by(IBMlab, catch.mult, Fhist, metric) %>%
  summarize(medval = median(value)) %>%
  mutate(Catch_mult = factor(catch.mult, level=c("0.75", "1")),
         F_history = ifelse(Fhist==1, "Fmsy", "2.5 x Fmsy"))

# 1000 point plots for long-term SSB/SSBmsy, F/Fmsy, and Catch/MSY  for Scenario CF1A only
simsfig5 <- sims %>%
  filter(metric %in% c("avg_ssb_ssbmsy","avg_f_fmsy","avg_catch_msy"),
         time.avg == "L",
         Scenlab == "CF1A") %>%
  select(isim, IBMlab, metric, value) %>%
  pivot_wider(names_from = metric, values_from = value)


# Figure labels for each PM
SSB_label <-expression(paste("SSB / ",SSB[MSY],sep = ""))
F_label <-expression(paste("F / ",F[MSY],sep = ""))
C_label <- "C / MSY"
IAV_label <- "Relative variability in catch (IAV)"
NING_label <- "Number of years overfishing"          
NED_label <- "Number of years overfished"            

# colors used to distinguish two types of points
point_cols <- c("black","dark gray")

# each figure can be generated by running the open curly bracket at the start of the fig
# set up to run on Windows currently, add quartz() on first line after curly bracket to run on Mac

# Figure 1 ---------------------------------------------------------------
# Alternative 4 boxplots showing only interquartile range and median
# have to adjust the upper range of values by hand, need to figure out a better way to do this if want to go with it
{
  pSSBalt4 <- ggplot(data=filter(sims, metric=="avg_ssb_ssbmsy"), aes(x=factor(IBMlab,level=IBM_order_new), y=value)) +
    geom_boxplot(outlier.shape = NA, coef = 0, fill="light gray") +
    theme_classic() +
    theme(text=element_text(family="Times"))+
    xlab("") + ylab(SSB_label) + ggtitle("A")+
    geom_hline(yintercept = 1) +
    coord_flip(ylim = c(0,3.5), expand=FALSE) 
  pFalt4 <- ggplot(data=filter(sims, metric=="avg_f_fmsy"), aes(x=factor(IBMlab,level=IBM_order_new), y=value)) +
    geom_boxplot(outlier.shape = NA, coef = 0, fill="light gray") +
    theme_classic() +
    theme(text=element_text(family="Times"))+
    xlab("") + ylab(F_label) + ggtitle("B")+
    geom_hline(yintercept = 1) +
    coord_flip(ylim = c(0,9), expand=FALSE) 
  pCalt4 <- ggplot(data=filter(sims, metric=="avg_catch_msy"), aes(x=factor(IBMlab,level=IBM_order_new), y=value)) +
    geom_boxplot(outlier.shape = NA, coef = 0, fill="light gray") +
    theme_classic() +
    theme(text=element_text(family="Times"))+
    xlab("") + ylab(C_label) + ggtitle("C")+
    geom_hline(yintercept = 1) +
    coord_flip(ylim = c(0,2), expand=FALSE) 
  pIAValt4 <- ggplot(data=filter(sims, metric=="iav_catch"), aes(x=factor(IBMlab,level=IBM_order_new), y=value)) +
    geom_boxplot(outlier.shape = NA, coef = 0, fill="light gray") +
    theme_classic() +
    theme(text=element_text(family="Times"))+
    xlab("") + ylab(IAV_label) + ggtitle("D")+
    coord_flip(ylim = c(0,1), expand=FALSE) 
  pINGalt4 <- ggplot(data=filter(sims, metric=="n_gr_fmsy"), aes(x=factor(IBMlab,level=IBM_order_new), y=value)) +
    geom_boxplot(outlier.shape = NA, coef = 0, fill="light gray") +
    theme_classic() +
    theme(text=element_text(family="Times"))+
    xlab("") + ylab(NING_label) + ggtitle("E")+
    coord_flip(ylim = c(0,26), expand=FALSE) 
  pEDalt4 <- ggplot(data=filter(sims, metric=="n_less_05_bmsy"), aes(x=factor(IBMlab,level=IBM_order_new), y=value)) +
    geom_boxplot(outlier.shape = NA, coef = 0, fill="light gray") +
    theme_classic() +
    theme(text=element_text(family="Times"))+
    xlab("") + ylab(NED_label) + ggtitle("F")+
    coord_flip(ylim = c(0,26), expand=FALSE) 
  p1alt4 <- grid.arrange(pSSBalt4,pFalt4,pCalt4,pIAValt4,pINGalt4,pEDalt4,nrow=3)
  ggsave("final_ms_figs/Figure_1.pdf",plot=p1alt4,device="pdf",width=7,height=8)
}

# Figure 2 --------------------------------------------------------------- 
# Median long term C/MSY vs SSB/SSBmsy
# with new data and DynLin label
{
  fig2new <- ggplot(medlong, aes(x=avg_ssb_ssbmsy, y=avg_catch_msy, color=retro_type)) +
    geom_point() +
    facet_wrap(~factor(IBMlab, level=rev(IBM_order_new))) +
    theme_classic() + 
    theme(text = element_text(family = "Times")) +
    labs(x=SSB_label, y=C_label) +
    scale_color_manual(values=point_cols)
  ggsave(filename = "final_ms_figs/Figure_2.pdf", plot=fig2new, device="pdf",width=6,height=6)
}

# Figure 3 ---------------------------------------------------------------
# PMs by F history and Retro source
# new version of Figure 3
{
  pSSB_retronew<-ggplot(data=filter(medretro_Fhist, metric=="avg_ssb_ssbmsy"), aes(x=factor(IBMlab,level=IBM_order_new), y=medval)) +
    geom_point((aes(colour = Retro_source, shape=F_history)))+
    theme_classic() + 
    theme(text=element_text(family="Times"))+
    xlab("") + ylab(SSB_label) + ggtitle("A")+
    geom_hline(yintercept = 1) +
    scale_color_manual(values=point_cols)+
    coord_flip()
  
  pF_retronew<-ggplot(data=filter(medretro_Fhist, metric=="avg_f_fmsy"), aes(x=factor(IBMlab,level=IBM_order_new), y=medval)) +
    geom_point((aes(colour = Retro_source, shape=F_history)))+
    theme_classic() + 
    theme(text=element_text(family="Times"))+
    xlab("") + ylab(F_label) + ggtitle("B")+
    geom_hline(yintercept = 1) +
    scale_color_manual(values=point_cols)+
    coord_flip()
  
  pC_retronew<-ggplot(data=filter(medretro_Fhist, metric=="avg_catch_msy"), aes(x=factor(IBMlab,level=IBM_order_new), y=medval)) +
    geom_point((aes(colour = Retro_source, shape=F_history)))+
    theme_classic() + 
    theme(text=element_text(family="Times"))+
    xlab("") + ylab(C_label) + ggtitle("C")+
    geom_hline(yintercept = 1) +
    scale_color_manual(values=point_cols)+
    coord_flip()
  
  pIAV_retronew<-ggplot(data=filter(medretro_Fhist, metric=="iav_catch"), aes(x=factor(IBMlab,level=IBM_order_new), y=medval)) +
    geom_point((aes(colour = Retro_source, shape=F_history)))+
    theme_classic() + 
    theme(text=element_text(family="Times"))+
    xlab("") + ylab(IAV_label) + ggtitle("D")+
    scale_color_manual(values=point_cols)+
    coord_flip()
  
  nING_retronew<-ggplot(data=filter(medretro_Fhist, metric=="n_gr_fmsy"), aes(x=factor(IBMlab,level=IBM_order_new), y=medval)) +
    geom_point((aes(colour = Retro_source, shape=F_history)))+
    theme_classic() + 
    theme(text=element_text(family="Times"))+
    xlab("") + ylab(NING_label) + ggtitle("E")+
    scale_color_manual(values=point_cols)+
    coord_flip()
  
  nED_retronew<-ggplot(data=filter(medretro_Fhist, metric=="n_less_05_bmsy"), aes(x=factor(IBMlab,level=IBM_order_new), y=medval)) +
    geom_point((aes(colour = Retro_source, shape=F_history)))+
    theme_classic() + 
    theme(text=element_text(family="Times"))+
    xlab("") + ylab(NED_label) + ggtitle("F")+
    scale_color_manual(values=point_cols)+
    coord_flip()
  
  p3n <-ggarrange(pSSB_retronew,pF_retronew,pC_retronew,pIAV_retronew,nING_retronew,nED_retronew, 
                 ncol=2, nrow=3, common.legend = TRUE, legend="bottom")
  ggsave("final_ms_figs/Figure_3.pdf",plot=p3n,device="pdf",width=7,height=8)
}

# Figure 4 ---------------------------------------------------------------
# F / Fmsy by Cmult, and  Short vs Long
# new Figure 4
{
  pF_time_Fhistnew<-ggplot(data=filter(medtime_Fhist, metric=="avg_f_fmsy"), aes(x=factor(IBMlab,level=IBM_order_new), y=medval)) +
    geom_point((aes(colour = Period, shape=F_history)))+
    theme_classic() + 
    theme(text=element_text(family="Times"))+
    xlab("") + ylab(F_label) + ggtitle("A")+
    geom_hline(yintercept = 1) +
    scale_color_manual(values=point_cols)+
    coord_flip()
  
  pF_Cmult_Fhistnew<-ggplot(data=filter(medCmult_Fhist, metric=="avg_f_fmsy"), aes(x=factor(IBMlab,level=IBM_order_new), y=medval)) +
    geom_point((aes(colour = Catch_mult, shape=F_history)))+
    theme_classic() + 
    theme(text=element_text(family="Times"))+
    xlab("") + ylab(F_label) + ggtitle("B")+
    geom_hline(yintercept = 1) +
    scale_color_manual(values=point_cols)+
    coord_flip()
  
  p4new <- grid.arrange(pF_time_Fhistnew,pF_Cmult_Fhistnew,nrow=2)
  ggsave("final_ms_figs/Figure_4.pdf",plot=p4new,device="pdf",width=6,height=6) }

# Figure 5 --------------------------------------------------------------- 
# original
# Long term C/MSY vs SSB/SSBmsy by realization and IBM
# uses scenario CF1A (see make_MS_tables_figures.R at bottom)
# new Figure 5
{
  fig5new <- ggplot(simsfig5, aes(x=avg_ssb_ssbmsy, y=avg_catch_msy)) +
    geom_point(alpha=0.15) +
    geom_vline(xintercept = 1, color="red", linetype="dashed") +
    geom_hline(yintercept = 1, color="red", linetype="dashed") +
    facet_wrap(~factor(IBMlab, level=rev(IBM_order_new))) +
    theme_classic() + 
    theme(text = element_text(family = "Times")) +
    labs(x=SSB_label, y=C_label)
  ggsave(filename = "final_ms_figs/Figure_5.pdf", plot=fig5new, device="pdf", width=6,height=6)
}



