---
title: "test kable for ibmwg"
author: "Liz Brooks"
date: "10/14/2020"
output: pdf_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Demo results

Here is a heatmap of all results so far, followed by a kable.  

``` {r echo=FALSE, results='asis', hide=TRUE, include=FALSE}
library(knitr)
#install.packages("gplots")
library(gplots)
setwd("C:/Users/liz.brooks/liz/R/IBMWG/demo_plots/results/")
source("demo_make_tables_figures_liz2.R", echo=FALSE, verbose=FALSE, local = knitr::knit_global())
s_met <- ssb_probs[ssb_probs$metric=="l_is_ge_bmsy",]
f_met <- f_probs[f_probs$metric=="l_is_less_fmsy",]
c_met <- catch_means[catch_means$metric=="l_avg_catch",]


#scen_meth_name <- paste0(s_met$IBMlab, "-", s_met$retro_type, s_met$catch.mult, "-F", s_met$Fhist, "-sel", s_met$n_selblocks )
scen_meth_name <- paste0(s_met$IBMlab, "-", s_met$Scenlab)

scf <- cbind(SSB=s_met$value, Catch=c_met$value, F=f_met$value)
rownames(scf) <- scen_meth_name


h1 <- heatmap.2(scf, scale="column", Colv=NA, margins=c(8,10))

demo_df <- as.data.frame(scf[h1$rowInd,])

```

The metrics plotted are probabilities that SSB is greather than or equal to SSBmsy, F is less than or equal to Fmsy, and the mean Catch/MSY. See figure \@ref(fig:heatmap-all).  I guess I need a newer version of Pandoc for the inline figure referencing to work.

```{r heatmap-all, fig.width = 13, fig.height = 20, out.width = "80%", out.height = "100%", fig.cap = "Heatmap of all methods and scenarios.  Clearly, it is challenging to scale this to be readable."}
heatmap(scf, scale="column", Colv=NA, margins=c(8,11))

kable(demo_df, caption="IBMWG kable, rows match the ordering from bottom of heatmap to the top. Label is a concatenation of IBMlabel, retro_type, catch.mult, Fhist, and n_selblocks. Only every other label is displayed on the heatmap.  The name of ExpandSurvey_modified should be shortened to something like ExpSurv--I don't see anything named ExpandSurvey, so the 'modified' begs what the unmodified method is.")
```

